import { Global, Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  AuthorityEntity,
  CollegeDepartmentEntity,
  CoordinatorCollegeDepartmentEntity,
  CoordinatorProfileEntity,
  CourseEntity,
  CourseTrainingSiteEntity,
  DepartmentEntity,
  DepartmentUnitEntity,
  EventEntity,
  HospitalEntity,
  NotificationEntity,
  PlacementEntity,
  SemesterEntity,
  StudentEvaluationEntity,
  StudentProfileEntity,
  SupervisorDepartmentUnitEntity,
  SupervisorEvaluationEntity,
  SupervisorProfileEntity,
  TrainingSiteEvaluationEntity,
  TrainingTimeSlotEntity,
  UserDocumentEntity,
  UserEntity,
} from 'entities/index.entity';

import {
  CoordinatorProfileRepositoryService,
  CourseTrainingSiteRepositoryService,
  CoursesRepositoryService,
  DepartmentRepositoryService,
  DepartmentUnitsRepositoryService,
  EventRepositoryService,
  HospitalRepositoryService,
  NotificationRepositoryService,
  PlacementRepositoryService,
  SemesterRepositoryService,
  StudentEvaluationRepositoryService,
  StudentProfileRepositoryService,
  SupervisorEvaluationRepositoryService,
  TrainingSiteEvaluationRepositoryService,
  TrainingTimeSlotRepositoryService,
  UserDocumentRepositoryService,
  UserRepositoryService,
  CoordinatorCollegeDepartmentRepositoryService,
  CollegeDepartmentRepositoryService,
  ClinicalSupervisorProfileRepositoryService,
  ClinicalSupervisorDepartmentUnitRepositoryService,
  AuthorityRepositoryService,
} from './services';

@Global()
@Module({
  imports: [
    TypeOrmModule.forFeature([
      UserEntity,
      UserDocumentEntity,
      TrainingTimeSlotEntity,
      TrainingSiteEvaluationEntity,
      SupervisorEvaluationEntity,
      StudentProfileEntity,
      StudentEvaluationEntity,
      SemesterEntity,
      PlacementEntity,
      NotificationEntity,
      HospitalEntity,
      EventEntity,
      DepartmentEntity,
      DepartmentUnitEntity,
      CourseEntity,
      CourseTrainingSiteEntity,
      CoordinatorProfileEntity,
      CoordinatorCollegeDepartmentEntity,
      CollegeDepartmentEntity,
      SupervisorProfileEntity,
      SupervisorDepartmentUnitEntity,
      AuthorityEntity,
    ]),
  ],
  providers: [
    UserRepositoryService,
    UserDocumentRepositoryService,
    TrainingTimeSlotRepositoryService,
    TrainingSiteEvaluationRepositoryService,
    SupervisorEvaluationRepositoryService,
    StudentProfileRepositoryService,
    StudentEvaluationRepositoryService,
    SemesterRepositoryService,
    PlacementRepositoryService,
    NotificationRepositoryService,
    HospitalRepositoryService,
    EventRepositoryService,
    DepartmentRepositoryService,
    DepartmentUnitsRepositoryService,
    CoursesRepositoryService,
    CourseTrainingSiteRepositoryService,
    CoordinatorProfileRepositoryService,
    CoordinatorCollegeDepartmentRepositoryService,
    CollegeDepartmentRepositoryService,
    ClinicalSupervisorProfileRepositoryService,
    ClinicalSupervisorDepartmentUnitRepositoryService,
    AuthorityRepositoryService,
  ],
  exports: [
    UserRepositoryService,
    UserDocumentRepositoryService,
    TrainingTimeSlotRepositoryService,
    TrainingSiteEvaluationRepositoryService,
    SupervisorEvaluationRepositoryService,
    StudentProfileRepositoryService,
    StudentEvaluationRepositoryService,
    SemesterRepositoryService,
    PlacementRepositoryService,
    NotificationRepositoryService,
    HospitalRepositoryService,
    EventRepositoryService,
    DepartmentRepositoryService,
    DepartmentUnitsRepositoryService,
    CoursesRepositoryService,
    CourseTrainingSiteRepositoryService,
    CoordinatorProfileRepositoryService,
    CoordinatorCollegeDepartmentRepositoryService,
    CollegeDepartmentRepositoryService,
    ClinicalSupervisorProfileRepositoryService,
    ClinicalSupervisorDepartmentUnitRepositoryService,
    AuthorityRepositoryService,
  ],
})
export class RepositoryModule {}
